export const json = (value, fallback = null) => {
  if (value == null) return fallback;
  if (typeof value !== "string") return value;
  try { return JSON.parse(value); } catch { return fallback; }
};

export async function ensureMaraRuntimeTables(store) {
  const kind = store.kind || (typeof store.activeDriver === "function" ? store.activeDriver() : "sqlite");
  const jsonType = kind === "postgres" ? "JSONB" : "TEXT";
  const timeType = kind === "postgres" ? "TIMESTAMPTZ" : "TEXT";
  const statements = [
    `CREATE TABLE IF NOT EXISTS agent_events (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,event_type TEXT NOT NULL,source_type TEXT NOT NULL,source_id TEXT,entity_type TEXT,entity_id TEXT,payload_json ${jsonType} NOT NULL,provenance_json ${jsonType} NOT NULL,confidence REAL NOT NULL,occurred_at ${timeType} NOT NULL,ingested_at ${timeType} NOT NULL,idempotency_key TEXT NOT NULL,processed_at ${timeType},UNIQUE(user_id,worker_id,idempotency_key))`,
    `CREATE TABLE IF NOT EXISTS worker_business_state_snapshots (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,state_version INTEGER NOT NULL,state_hash TEXT NOT NULL,state_json ${jsonType} NOT NULL,material_changes_json ${jsonType} NOT NULL,source_event_watermark ${timeType},created_at ${timeType} NOT NULL,UNIQUE(user_id,worker_id,state_version))`,
    `CREATE TABLE IF NOT EXISTS agent_work_candidates (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,candidate_type TEXT NOT NULL,trigger_event_ids_json ${jsonType} NOT NULL,possible_commercial_objective TEXT NOT NULL,urgency TEXT NOT NULL,dependencies_json ${jsonType} NOT NULL,suggested_owner TEXT NOT NULL,required_capabilities_json ${jsonType} NOT NULL,user_action_may_be_required INTEGER NOT NULL,risk_class TEXT NOT NULL,evidence_json ${jsonType} NOT NULL,dedupe_key TEXT NOT NULL,expires_at ${timeType},status TEXT NOT NULL,created_at ${timeType} NOT NULL,UNIQUE(user_id,worker_id,dedupe_key))`,
    `CREATE TABLE IF NOT EXISTS agent_planning_runs (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,mode TEXT NOT NULL,state_snapshot_id TEXT,state_hash TEXT,trigger_event_ids_json ${jsonType} NOT NULL,playbook_versions_json ${jsonType} NOT NULL,planner_input_json ${jsonType} NOT NULL,planner_output_json ${jsonType},legacy_plan_json ${jsonType} NOT NULL,diagnostics_json ${jsonType} NOT NULL,provider TEXT,model TEXT,estimated_cost_usd REAL NOT NULL,status TEXT NOT NULL,created_at ${timeType} NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS model_usage_events (id TEXT PRIMARY KEY,user_id TEXT,worker_id TEXT,task_type TEXT NOT NULL,provider TEXT NOT NULL,model TEXT NOT NULL,input_tokens INTEGER NOT NULL,output_tokens INTEGER NOT NULL,cached_tokens INTEGER NOT NULL,estimated_cost_usd REAL NOT NULL,latency_ms INTEGER NOT NULL,retry_count INTEGER NOT NULL,request_status TEXT NOT NULL,acceptance_status TEXT NOT NULL,related_event_id TEXT,related_task_id TEXT,related_opportunity_id TEXT,related_commercial_outcome_id TEXT,request_id TEXT,created_at ${timeType} NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS agent_tasks_v2 (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,owner TEXT NOT NULL,task_kind TEXT NOT NULL,source_plan_id TEXT NOT NULL,source_state_hash TEXT,source_event_ids_json ${jsonType} NOT NULL,source_candidate_types_json ${jsonType} NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,commercial_objective TEXT NOT NULL,expected_business_effect TEXT NOT NULL,priority TEXT NOT NULL,urgency TEXT NOT NULL,creator_effort_minutes INTEGER NOT NULL,estimated_mara_cost_usd REAL NOT NULL,required_capabilities_json ${jsonType} NOT NULL,required_tools_json ${jsonType} NOT NULL,approval_requirement TEXT NOT NULL,execution_tier TEXT NOT NULL,scheduled_at ${timeType},scheduled_window TEXT,duration_minutes INTEGER NOT NULL,timezone TEXT NOT NULL,completion_condition TEXT NOT NULL,reassessment_trigger TEXT NOT NULL,expiration_rule_json ${jsonType} NOT NULL,expires_at ${timeType},confidence REAL NOT NULL,status TEXT NOT NULL,failure_state_json ${jsonType},retry_policy_json ${jsonType} NOT NULL,idempotency_key TEXT NOT NULL,output_json ${jsonType},execution_claim_id TEXT,execution_claimed_at ${timeType},attempt_count INTEGER NOT NULL,completed_at ${timeType},created_at ${timeType} NOT NULL,updated_at ${timeType} NOT NULL,UNIQUE(user_id,worker_id,idempotency_key))`,
    `CREATE TABLE IF NOT EXISTS agent_task_relationships (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,from_task_id TEXT NOT NULL,to_task_id TEXT NOT NULL,relationship_type TEXT NOT NULL,metadata_json ${jsonType} NOT NULL,created_at ${timeType} NOT NULL,UNIQUE(user_id,worker_id,from_task_id,to_task_id,relationship_type))`,
    `CREATE TABLE IF NOT EXISTS agent_task_audit_history (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,task_id TEXT NOT NULL,event_type TEXT NOT NULL,from_status TEXT,to_status TEXT,reason TEXT,metadata_json ${jsonType} NOT NULL,created_at ${timeType} NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS agent_task_calendar_entries (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,task_id TEXT NOT NULL,calendar_owner TEXT NOT NULL,starts_at ${timeType} NOT NULL,ends_at ${timeType} NOT NULL,timezone TEXT NOT NULL,status TEXT NOT NULL,idempotency_key TEXT NOT NULL,created_at ${timeType} NOT NULL,updated_at ${timeType} NOT NULL,UNIQUE(user_id,worker_id,idempotency_key))`,
    `CREATE TABLE IF NOT EXISTS agent_task_compilation_runs (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,source_plan_id TEXT NOT NULL,mode TEXT NOT NULL,report_json ${jsonType} NOT NULL,status TEXT NOT NULL,created_at ${timeType} NOT NULL,UNIQUE(user_id,worker_id,source_plan_id,mode))`,
    `CREATE TABLE IF NOT EXISTS agent_task_execution_attempts (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,task_id TEXT NOT NULL,claim_id TEXT NOT NULL,execution_tier TEXT NOT NULL,status TEXT NOT NULL,result_json ${jsonType},error_json ${jsonType},started_at ${timeType} NOT NULL,completed_at ${timeType},UNIQUE(user_id,worker_id,task_id,claim_id))`,
    `CREATE TABLE IF NOT EXISTS agent_dynamic_responsibilities (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,title TEXT NOT NULL,commercial_objective TEXT NOT NULL,cadence_json ${jsonType} NOT NULL,candidate_trigger_type TEXT NOT NULL,is_active INTEGER NOT NULL,last_triggered_at ${timeType},next_check_at ${timeType},idempotency_key TEXT NOT NULL,created_at ${timeType} NOT NULL,updated_at ${timeType} NOT NULL,UNIQUE(user_id,worker_id,idempotency_key))`,
    `CREATE TABLE IF NOT EXISTS agent_briefings_v2 (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,worker_id TEXT NOT NULL,period_start ${timeType} NOT NULL,period_end ${timeType} NOT NULL,briefing_json ${jsonType} NOT NULL,source_task_ids_json ${jsonType} NOT NULL,source_event_ids_json ${jsonType} NOT NULL,created_at ${timeType} NOT NULL)`
  ];
  for (const statement of statements) await store.execute(statement);
}
