import test from "node:test";
import assert from "node:assert/strict";
import { createStore } from "./dataStore.mjs";
import { MARA_PHASE2_SCENARIOS } from "./maraPhase2Scenarios.mjs";
import { generateCandidateWork } from "./maraCandidateWork.mjs";
import { compileMaraPlan } from "./maraPlanTaskCompiler.mjs";
import { listCalendar } from "./maraDeterministicScheduler.mjs";
import { executeInternalTask, recoverStaleExecutionClaims } from "./maraControlledExecution.mjs";
import { reassessTaskGraph } from "./maraReassessment.mjs";
import { createMaraBriefing } from "./maraBriefings.mjs";
import { listTaskAudit, listTaskGraph, transitionTask } from "./maraTaskGraph.mjs";
import { registerDynamicResponsibility, materializeDueResponsibilities } from "./maraPhase3Runtime.mjs";
import { ingestMaraEvent, listMaraEvents } from "./maraEvents.mjs";

const planningTime = "2026-07-15T13:00:00.000Z";
const tools = ["internal_read","internal_records","internal_task_create","internal_artifact","analytics","research","contact_validation"];
function work(type, scenario, overrides={}) {
  const objective=generateCandidateWork(scenario.state).find((c)=>c.candidateType===type)?.possibleCommercialObjective || "Make measurable progress toward legitimate creator income";
  return {title:`Handle ${type.replaceAll("_"," ")}`,sourceCandidateTypes:[type],owner:"mara",commercialObjective:objective,expectedBusinessEffect:`Resolve ${type} using current business evidence`,urgency:"high",creatorEffortMinutes:0,dependencies:[],scheduledTime:null,schedulingWindow:"next available work block",approvalRequirement:"none",executionModelTier:"code",completionCondition:"An internal evidence-backed result is recorded",reassessmentTrigger:"Relevant business state or outcome changes",confidence:.88,evidence:[type],...overrides};
}
function planFor(scenario) {
  const candidates=generateCandidateWork(scenario.state); const preferred=scenario.expected.filter((type)=>candidates.some((c)=>c.candidateType===type));
  const selected=preferred.length?preferred.slice(0,scenario.id==="historical-import"?2:1):[];
  const workToCreate=selected.map((type)=>work(type,scenario,{creatorEffortMinutes:0}));
  if (scenario.id==="strong-content-no-replies" && workToCreate[0]) workToCreate[0].title="Diagnose replies and contact deliverability";
  if (scenario.id==="low-response" && workToCreate[0]) workToCreate[0].title="Diagnose segment and value proposition response";
  if (scenario.id==="urgent-active-deals") workToCreate.push(work("protect_active_deadline",scenario,{title:"Creator reviews final deadline package",owner:"creator",creatorEffortMinutes:15,dependencies:[workToCreate[0].title],executionModelTier:"code",approvalRequirement:"creator confirms final deliverable"}));
  if (scenario.id==="limited-time" && workToCreate[0]) Object.assign(workToCreate[0],{owner:"creator",creatorEffortMinutes:10,schedulingWindow:"Sunday 14:00-16:00"});
  return {situationSummary:scenario.name,currentBottleneck:selected[0]||"No justified new work",emergingNeeds:[],workToCreate,workToSkip:scenario.avoid.map((item)=>({work:item,reason:"Not supported by current state"})),questionsForUser:[]};
}
function inputFor(scenario) { return {userId:`u-${scenario.id}`,workerId:"mara",planningTime,timeZone:"America/New_York",businessState:scenario.state,meaningfulRecentEvents:[],candidateWork:generateCandidateWork(scenario.state),playbooks:[],availableTools:tools,permissions:{externalCommunication:false},budget:{maxUsd:.5},existingScheduledWork:[]}; }
async function setup(){const store=createStore({databasePath:":memory:"});await store.init();return store;}

test("16 accepted behavioral plans compile into distinct, commercially grounded graphs",async()=>{
  const signatures=new Set();
  for(const scenario of MARA_PHASE2_SCENARIOS){const store=await setup();const input=inputFor(scenario);const result=await compileMaraPlan(store,{userId:input.userId,workerId:"mara",planId:`p-${scenario.id}`,stateHash:`s-${scenario.id}`,plan:planFor(scenario),plannerInput:input,mode:"task_creation",env:{MARA_DISCOVERY_PAUSE_BACKLOG:"20"}});const tasks=await listTaskGraph(store,{userId:input.userId,workerId:"mara"});
    assert.ok(tasks.every((task)=>task.commercialObjective&&task.completionCondition&&task.reassessmentTrigger));
    assert.ok(!tasks.some((task)=>/gmail|send email/i.test(task.title))); signatures.add(tasks.map((t)=>`${t.owner}:${t.title}`).join("|"));
    if(scenario.id==="strong-portfolio"||scenario.id==="portfolio-alone") assert.ok(!tasks.some((t)=>/portfolio|media kit/i.test(t.title)));
    if(scenario.id==="twenty-unsent") assert.ok(!tasks.some((t)=>/strengthen pipeline|discover/i.test(t.title)));
    if(scenario.id==="limited-time") assert.ok(tasks.reduce((n,t)=>n+t.creatorEffortMinutes,0)<=10);
    if(scenario.id==="portfolio-alone") assert.equal(tasks.length,0);
    assert.equal(result.report.rejected.length,0); await store.close();
  }
  assert.equal(signatures.size,16);
});

test("compiler creates separate calendars, orders dependencies, deduplicates replay, and repairs a missing calendar",async()=>{const scenario=MARA_PHASE2_SCENARIOS.find((s)=>s.id==="urgent-active-deals");const store=await setup();const input=inputFor(scenario);const reversedPlan=planFor(scenario);reversedPlan.workToCreate.reverse();const args={userId:input.userId,workerId:"mara",planId:"plan-a",stateHash:"same-state",plan:reversedPlan,plannerInput:input,mode:"task_creation"};const first=await compileMaraPlan(store,args);const second=await compileMaraPlan(store,{...args,planId:"plan-b"});let mara=await listCalendar(store,{userId:input.userId,workerId:"mara",calendarOwner:"mara"});let creator=await listCalendar(store,{userId:input.userId,workerId:"mara",calendarOwner:"creator"});assert.equal(first.report.created.length,2);assert.equal(second.report.reused.length,2);assert.equal((await listTaskGraph(store,{userId:input.userId,workerId:"mara"})).length,2);assert.equal(mara.length,1);assert.equal(creator.length,1);assert.ok(new Date(creator[0].starts_at)>=new Date(mara[0].ends_at));await store.execute("DELETE FROM agent_task_calendar_entries WHERE id=?",creator[0].id);await compileMaraPlan(store,{...args,planId:"plan-c"});mara=await listCalendar(store,{userId:input.userId,workerId:"mara",calendarOwner:"mara"});creator=await listCalendar(store,{userId:input.userId,workerId:"mara",calendarOwner:"creator"});assert.equal(mara.length,1);assert.equal(creator.length,1);await store.close();});

test("compiler rejects external action and circular or missing dependencies before persistence",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const store=await setup();const input=inputFor(scenario);const forbidden=planFor(scenario);forbidden.workToCreate=[work("strengthen_pipeline",scenario,{title:"Send email to brand",completionCondition:"Email sent"})];await assert.rejects(()=>compileMaraPlan(store,{userId:input.userId,planId:"bad",stateHash:"x",plan:forbidden,plannerInput:input,mode:"task_creation"}),/prohibited external execution/);assert.equal((await listTaskGraph(store,{userId:input.userId,workerId:"mara"})).length,0);const missing=planFor(scenario);missing.workToCreate[0].dependencies=["not a task"];await assert.rejects(()=>compileMaraPlan(store,{userId:input.userId,planId:"missing",stateHash:"y",plan:missing,plannerInput:input,mode:"task_creation"}),/Unknown task dependency/);const circular=planFor(scenario);circular.workToCreate=[work("strengthen_pipeline",scenario,{title:"Task A",dependencies:["Task B"]}),work("strengthen_pipeline",scenario,{title:"Task B",dependencies:["Task A"]})];await assert.rejects(()=>compileMaraPlan(store,{userId:input.userId,planId:"circle",stateHash:"z",plan:circular,plannerInput:input,mode:"task_creation"}),/circular dependency/);await store.close();});

test("controlled execution is allowlisted, dependency-safe, accepted, and exactly once",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const store=await setup();const input=inputFor(scenario);const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"exec",stateHash:"exec",plan:planFor(scenario),plannerInput:input,mode:"task_creation"});const task=compiled.tasks[0];const denied=await executeInternalTask(store,{userId:input.userId,taskId:task.id,executors:{code:async()=>({accepted:true})},allowedUserIds:[]});assert.equal(denied.status,"denied");const done=await executeInternalTask(store,{userId:input.userId,taskId:task.id,executors:{code:async()=>({accepted:true,artifact:{type:"internal_analysis"}})},allowedUserIds:[input.userId]});assert.equal(done.status,"completed");const again=await executeInternalTask(store,{userId:input.userId,taskId:task.id,executors:{code:async()=>{throw new Error("must not run");}},allowedUserIds:[input.userId]});assert.equal(again.status,"reused");assert.equal((await store.query("SELECT * FROM agent_task_execution_attempts")).length,1);await store.close();});

test("timeouts and partial low-quality results fail safely and remain retryable only when allowed",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const store=await setup();const input=inputFor(scenario);const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"failure",stateHash:"failure",plan:planFor(scenario),plannerInput:input,mode:"task_creation"});const task=compiled.tasks[0];const timeout=await executeInternalTask(store,{userId:input.userId,taskId:task.id,executors:{code:async()=>new Promise(()=>{})},allowedUserIds:[input.userId],timeoutMs:5});assert.equal(timeout.failure.code,"timeout");assert.equal((await executeInternalTask(store,{userId:input.userId,taskId:task.id,executors:{code:async()=>({accepted:true})},allowedUserIds:[input.userId]})).status,"backoff");await store.execute("UPDATE agent_tasks_v2 SET failure_state_json=? WHERE id=?",JSON.stringify({...timeout.failure,retryAfter:"2026-07-15T00:00:00Z"}),task.id);const partial=await executeInternalTask(store,{userId:input.userId,taskId:task.id,executors:{code:async()=>({accepted:false,partial:"unsafe to publish"})},allowedUserIds:[input.userId]});assert.equal(partial.failure.code,"quality_threshold");assert.equal(partial.failure.retryable,false);assert.equal((await executeInternalTask(store,{userId:input.userId,taskId:task.id,executors:{code:async()=>({accepted:true})},allowedUserIds:[input.userId]})).status,"non_retryable");await store.close();});

test("stale claims recover after restart without duplicate execution",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const store=await setup();const input=inputFor(scenario);const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"restart",stateHash:"restart",plan:planFor(scenario),plannerInput:input,mode:"task_creation"});const id=compiled.tasks[0].id;await store.execute("UPDATE agent_tasks_v2 SET status='running',execution_claim_id='dead',execution_claimed_at=? WHERE id=?","2026-07-15T10:00:00Z",id);assert.equal(await recoverStaleExecutionClaims(store,{now:new Date(planningTime)}),1);const result=await executeInternalTask(store,{userId:input.userId,taskId:id,executors:{code:async()=>({accepted:true})},allowedUserIds:[input.userId]});assert.equal(result.status,"completed");await store.close();});

test("new outcomes invalidate only relevant tasks; availability changes reschedule creator work",async()=>{const scenario=MARA_PHASE2_SCENARIOS.find((s)=>s.id==="overdue-payment");const store=await setup();const input=inputFor(scenario);const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"reassess",stateHash:"a",plan:planFor(scenario),plannerInput:input,mode:"task_creation"});const report=await reassessTaskGraph(store,{userId:input.userId,events:[{id:"paid",eventType:"payment_received"}],state:scenario.state,planningTime});assert.deepEqual(report.invalidated,[compiled.tasks[0].id]);const audit=await listTaskAudit(store,{userId:input.userId,workerId:"mara",taskId:compiled.tasks[0].id});assert.ok(audit.some((row)=>row.to_status==="invalidated"));await store.close();});

test("briefings contain only persisted events and task results",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const store=await setup();const input=inputFor(scenario);const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"brief",stateHash:"brief",plan:planFor(scenario),plannerInput:input,mode:"task_creation"});await executeInternalTask(store,{userId:input.userId,taskId:compiled.tasks[0].id,executors:{code:async()=>({accepted:true,summary:"Evidence recorded"})},allowedUserIds:[input.userId]});const briefing=await createMaraBriefing(store,{userId:input.userId,periodStart:"2026-07-14T00:00:00Z",periodEnd:new Date(Date.now()+60_000).toISOString()});assert.equal(briefing.completed.length,1);assert.equal(briefing.completed[0].result.summary,"Evidence recorded");await store.close();});

test("a transient database failure rolls back cleanly and retry creates one graph",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const base=await setup();const input=inputFor(scenario);let fail=true;const store={...base,tx:(callback)=>base.tx((tx)=>callback({...tx,execute:async(sql,...params)=>{if(fail&&sql.includes("INSERT INTO agent_tasks_v2")){fail=false;throw new Error("injected database retry");}return tx.execute(sql,...params);}}))};const args={userId:input.userId,planId:"db-retry",stateHash:"db-retry",plan:planFor(scenario),plannerInput:input,mode:"task_creation"};await assert.rejects(()=>compileMaraPlan(store,args),/injected database retry/);await compileMaraPlan(store,args);assert.equal((await listTaskGraph(base,{userId:input.userId,workerId:"mara"})).length,1);await base.close();});

test("blocked work does not freeze unrelated work",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const store=await setup();const input=inputFor(scenario);const plan=planFor(scenario);plan.workToCreate.push(work("interpret_content_performance",scenario,{title:"Analyze unrelated evidence"}));const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"blocked",stateHash:"blocked",plan,plannerInput:input,mode:"task_creation"});await transitionTask(store,{userId:input.userId,workerId:"mara",taskId:compiled.tasks[0].id,toStatus:"blocked",reason:"Missing narrow input"});const result=await executeInternalTask(store,{userId:input.userId,taskId:compiled.tasks[1].id,executors:{code:async()=>({accepted:true})},allowedUserIds:[input.userId]});assert.equal(result.status,"completed");await store.close();});

test("creator availability reschedules creator work and expired approvals stop",async()=>{const scenario=MARA_PHASE2_SCENARIOS.find((s)=>s.id==="limited-time");const store=await setup();const input=inputFor(scenario);const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"availability",stateHash:"availability",plan:planFor(scenario),plannerInput:input,mode:"task_creation"});const before=await listCalendar(store,{userId:input.userId,workerId:"mara",calendarOwner:"creator"});const state={...scenario.state,capacity:{...scenario.state.capacity,availableWindows:["Saturday 09:00"]}};const changed=await reassessTaskGraph(store,{userId:input.userId,events:[{id:"available",eventType:"creator_availability_changed"}],state,planningTime});assert.deepEqual(changed.rescheduled,[compiled.tasks[0].id]);const after=await listCalendar(store,{userId:input.userId,workerId:"mara",calendarOwner:"creator"});assert.equal(before.length,1);assert.equal(after.length,1);assert.notEqual(after[0].starts_at,before[0].starts_at);await store.execute("UPDATE agent_tasks_v2 SET expires_at=? WHERE id=?","2026-07-15T12:00:00Z",compiled.tasks[0].id);const expired=await reassessTaskGraph(store,{userId:input.userId,events:[],state,planningTime});assert.deepEqual(expired.expired,[compiled.tasks[0].id]);await store.close();});

test("results are discarded when a task is invalidated during execution",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const store=await setup();const input=inputFor(scenario);const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"race",stateHash:"race",plan:planFor(scenario),plannerInput:input,mode:"task_creation"});const id=compiled.tasks[0].id;const result=await executeInternalTask(store,{userId:input.userId,taskId:id,allowedUserIds:[input.userId],executors:{code:async()=>{await transitionTask(store,{userId:input.userId,workerId:"mara",taskId:id,toStatus:"invalidated",reason:"New evidence arrived"});return {accepted:true,stale:true};}}});assert.equal(result.status,"invalidated_during_execution");assert.equal(result.task.status,"invalidated");assert.equal(result.task.output,null);await store.close();});

test("shadow compilation persists nothing and model-tier timeout fails closed",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const store=await setup();const input=inputFor(scenario);const shadow=await compileMaraPlan(store,{userId:input.userId,planId:"shadow",stateHash:"shadow",plan:planFor(scenario),plannerInput:input,mode:"shadow"});assert.equal(shadow.tasks.length,1);assert.equal((await listTaskGraph(store,{userId:input.userId,workerId:"mara"})).length,0);const plan=planFor(scenario);plan.workToCreate[0].executionModelTier="small";const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"model-timeout",stateHash:"model-timeout",plan,plannerInput:input,mode:"task_creation"});const result=await executeInternalTask(store,{userId:input.userId,taskId:compiled.tasks[0].id,allowedUserIds:[input.userId],executors:{small:async()=>new Promise(()=>{})},timeoutMs:5});assert.equal(result.failure.code,"timeout");await store.close();});

test("shared work is resolved without hidden creator effort and blocking questions become information tasks",async()=>{const scenario=MARA_PHASE2_SCENARIOS[1];const store=await setup();const input=inputFor(scenario);const plan=planFor(scenario);plan.workToCreate[0].owner="shared";plan.workToCreate[0].creatorEffortMinutes=12;plan.questionsForUser=["Which payment account should the internal invoice reference?"];const compiled=await compileMaraPlan(store,{userId:input.userId,planId:"owners",stateHash:"owners",plan,plannerInput:input,mode:"task_creation"});assert.equal(compiled.tasks.length,2);assert.ok(compiled.tasks.every((task)=>task.owner==="creator"));assert.ok(compiled.tasks.some((task)=>task.taskKind==="information_request"&&task.status==="awaiting_information"));await store.close();});

test("recurring responsibilities emit idempotent events and advance cadence instead of fixed tasks",async()=>{const store=await setup();await registerDynamicResponsibility(store,{userId:"recurring",title:"Check overdue revenue",commercialObjective:"Protect earned revenue",cadence:{intervalDays:7},candidateTriggerType:"invoice_due",nextCheckAt:"2026-07-15T12:00:00Z"});const emitEvent=(event)=>ingestMaraEvent(store,event);assert.equal((await materializeDueResponsibilities(store,{userId:"recurring",now:planningTime,emitEvent})).length,1);assert.equal((await materializeDueResponsibilities(store,{userId:"recurring",now:planningTime,emitEvent})).length,0);assert.equal((await listMaraEvents(store,{userId:"recurring",workerId:"mara"})).length,1);const row=await store.queryOne("SELECT is_active,next_check_at FROM agent_dynamic_responsibilities WHERE user_id=?","recurring");assert.equal(Number(row.is_active),1);assert.equal(row.next_check_at,"2026-07-22T12:00:00.000Z");await store.close();});
