import path from "node:path";

/**
 * Resolve a tenant-owned upload without allowing either identifier to escape
 * the configured upload root. Stored names are generated by Ryva, but this
 * validation keeps corrupted or legacy database rows from becoming a path
 * traversal primitive.
 */
export function resolveUserUploadPath(uploadsRoot, userId, storedName) {
  const safeUserId = String(userId ?? "").trim();
  const safeStoredName = path.basename(String(storedName ?? "").trim());
  if (!safeUserId || safeUserId !== path.basename(safeUserId) || !safeStoredName) {
    throw new Error("Invalid upload path.");
  }
  return path.join(uploadsRoot, safeUserId, safeStoredName);
}
