import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

void describe("Ryva Analytics", () => {
  void it("workspace preserves analytics routes, views, and evidence boundaries", () => {
    const source = readFileSync(new URL("./AnalyticsWorkspace.tsx", import.meta.url), "utf8");
    assert.match(source, /title="Analytics"/);
    assert.match(source, /Wholesale performance across outreach, placements, and verified sales\./);
    assert.match(source, /Representative Performance/);
    assert.match(source, /Product Performance/);
    assert.match(source, /Brand Performance/);
    assert.match(source, /Buyer Performance/);
    assert.match(source, /Pipeline Analytics/);
    assert.match(source, /Commercial Analytics/);
    assert.match(source, /Portfolio Health/);
    assert.match(source, /Metric guide/);
    assert.match(source, /Definitions, formulas, and data rules for every Analytics metric\./);
    assert.match(source, /definitionExpandFields/);
    assert.match(source, /How it’s calculated/);
    assert.match(source, /ry-analytics-guide-list/);
    assert.match(source, /aria-expanded/);
    assert.match(source, /definitionDescription/);
    assert.doesNotMatch(source, /Business meaning/);
    assert.doesNotMatch(source, /Included records/);
    assert.doesNotMatch(source, /Known limitations/);
    assert.match(source, />Apply</);
    assert.match(source, /Export data/);
    assert.doesNotMatch(source, /Metric Definitions/);
    assert.doesNotMatch(source, /Export permitted CSV/);
    assert.doesNotMatch(source, />Recalculate</);
    assert.match(source, /\/api\/analytics\?\$\{query\}/);
    assert.match(source, /\/api\/analytics\/export/);
    assert.match(source, /\/api\/analytics\/reports/);
    assert.match(source, /method: "POST"/);
    assert.match(source, /Currencies are shown separately\./);
    assert.match(source, /Commission summary/);
    assert.match(source, /Track commissions from expected through payment\./);
    assert.match(source, /formatMoneyByCurrency/);
    assert.match(source, /Stage detail/);
    assert.match(source, /formatStageDetailValue/);
    assert.match(source, /Download a CSV for any Analytics tab/);
    assert.doesNotMatch(source, /exports are audited/);
    assert.doesNotMatch(source, /formatMoney\(sumNumericField\(orders, "verified"\)\)/);
    assert.doesNotMatch(source, /Grouped by ISO currency; currencies are never combined\./);
    assert.doesNotMatch(source, /title="Expected commission"/);
    assert.match(source, /Weighted pipeline disabled/);
    assert.match(source, /No verified external intelligence is connected/);
    assert.match(source, /StatusLabel value=\{data\.externalIntelligence\.status\}/);
    assert.match(source, /ForecastRange/);
    assert.match(source, /Outreach sent/);
    assert.match(source, /Performance overview/);
    assert.match(source, /Messages approved/);
    assert.match(source, /Delivery health/);
    assert.match(source, /Positive replies/);
    assert.match(source, /Stalled placements/);
    assert.match(source, /RATE_METRIC_CODES/);
    assert.match(source, /of active placements/);
    assert.match(source, /metricDisplay\(data\.metrics\[code\], code\)/);
    assert.match(source, /Portfolio health/);
    assert.match(source, /Monitor active accounts, reorder activity, and commercial risk\./);
    assert.match(source, /portfolioNeedsAttention/);
    assert.match(source, /Your portfolio looks healthy\./);
    assert.match(source, /Accounts at risk/);
    assert.match(source, /Reorders due soon/);
    assert.doesNotMatch(source, /Context, not a universal health score/);
    assert.doesNotMatch(source, /Review Brands/);
    assert.match(source, /PIPELINE_VISUAL_STAGES/);
    assert.match(source, /pipelineStageBuckets/);
    assert.match(source, /pipelineAttentionItems/);
    assert.match(source, /Needs attention/);
    assert.match(source, /days inactive/);
    assert.match(source, /DAYS_INACTIVE_HINT/);
    assert.match(source, /Targeted/);
    assert.match(source, /Negotiating/);
    assert.match(source, /See how products are progressing through placements and verified sales\./);
    assert.match(source, /Verified sales/);
    assert.match(source, /Evidence needing review/);
    assert.match(source, /brandPerformanceRows/);
    assert.match(source, /Commission issues/);
    assert.match(source, /BRAND_COLUMN_LABELS/);
    assert.match(source, /MONEY_COLUMNS/);
    assert.match(source, /formatAnalyticsCell/);
    assert.match(source, /title="Buyer performance"/);
    assert.match(source, /analyticsColumnLabel/);
    assert.doesNotMatch(source, /Buyer and Business performance/);
    assert.doesNotMatch(source, /Verified value/);
    assert.doesNotMatch(source, /Avg\. idle time/);
    assert.doesNotMatch(source, /pipelineHealthSentence/);
    assert.doesNotMatch(source, /description="Platform outcomes describe the recorded Ryva context/);
    assert.doesNotMatch(source, /label: "Brands"/);
    assert.doesNotMatch(source, />At a glance</);
  });

  void it("uses token-only analytics styling without clipping content", () => {
    const css = readFileSync(new URL("./analytics.css", import.meta.url), "utf8");
    assert.match(css, /64rem/);
    assert.match(css, /48rem/);
    assert.match(css, /var\(--color-border\)/);
    assert.match(css, /ry-analytics-guide-list/);
    assert.match(css, /ry-analytics-guide-detail/);
    assert.doesNotMatch(css, /overflow-x:\s*hidden/);
  });

  void it("exports the analytics workspace", () => {
    const source = readFileSync(new URL("./index.ts", import.meta.url), "utf8");
    assert.match(source, /AnalyticsWorkspacePage/);
  });

  void it("keeps domain boundaries honest in source contracts", () => {
    const analytics = readFileSync(new URL("./AnalyticsWorkspace.tsx", import.meta.url), "utf8");
    const transferImport = readFileSync(new URL("../transfer/ImportReview.tsx", import.meta.url), "utf8");
    const transferExport = readFileSync(new URL("../transfer/ExportReview.tsx", import.meta.url), "utf8");
    const admin = readFileSync(new URL("../admin/OperationsWorkspace.tsx", import.meta.url), "utf8");
    assert.match(analytics, /Unavailable — denominator or provider data is absent/);
    assert.match(analytics, /partialData/);
    assert.doesNotMatch(analytics, /industry average|close probability|revenue projection/i);
    assert.match(transferImport, /Preview import/);
    assert.match(transferImport, /Approve exact preview and commit/);
    assert.doesNotMatch(transferImport, /Validate preview/);
    assert.doesNotMatch(transferImport, /rolled back automatically|validation commits/i);
    assert.match(transferExport, /Export queued/);
    assert.match(transferExport, /Download export/);
    assert.match(admin, /lastErrorSafe/);
    assert.doesNotMatch(admin, /stackTrace|access_token|client_secret/i);
  });
});
